name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome to the Minecraft Modding Community on github! If you can't get the modpack to load - do you know how to install it?"
        pr-message: "You a good mod user? make sure you understand how curseforge works before attempting this."
